apiVersion: v1
kind: Service
metadata:
  name: devops-app-metrics
  labels:
    app: devops-app
spec:
  selector:
    app: devops-app
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-app-monitor
  labels:
    app: devops-app
spec:
  selector:
    matchLabels:
      app: devops-app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
